spring.application.name=comeycalla-backend

spring.datasource.url=jdbc:mariadb://localhost:3307/comeycalla
spring.datasource.username=comeycalla_user
spring.datasource.password=comeycalla_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=BVauEv1RJ0qNJdgigan5w9xNURm9nY0iQr7JUZ3PE3x
app.jwt.expiration=86400000